services:

  submission-db:
    image: mysql:8.0
    container_name: submission_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: submission_db
    ports:
      - "3307:3306"
    volumes:
      - submission_db_data:/var/lib/mysql

  submission-service:
    build: ./backend/submission-service
    container_name: submission_service
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - submission-db
      - conference-service
    env_file:
      - ./backend/submission-service/.env
    environment:
      DATABASE_URL: mysql+pymysql://root:root@submission-db:3306/submission_db
      NOTIFICATION_SERVICE_URL: http://notification-service:8000/notifications/send
      CONFERENCE_SERVICE_URL: http://conference-service:8000/conferences
      INTELLIGENT_SERVICE_URL: http://intelligent-service:8004/intelligent
      
    volumes:
      - ./backend/submission-service/uploads:/app/uploads

  notification-db:
    image: mysql:8.0
    container_name: notification_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notification_db
    ports:
      - "3308:3306"
    volumes:
      - notification_db_data:/var/lib/mysql

  notification-service:
    build: ./backend/notification-service
    container_name: notification_service
    restart: on-failure
    ports:
      - "8001:8000"
    depends_on:
      - notification-db
    env_file:
      - ./backend/notification-service/.env
    environment:
      DATABASE_URL: mysql+pymysql://root:root@notification-db:3306/notification_db

  conference-db:
    image: mysql:8.0
    container_name: conference_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: conference_db
    ports:
      - "3309:3306"
    volumes:
      - conference_db_data:/var/lib/mysql

  conference-service:
    build: 
      context: ./backend/conference-service 
      dockerfile: Dockerfile
    container_name: conference_service
    restart: on-failure
    ports:
      - "8002:8000" 
    depends_on:
      - conference-db
    env_file:
      - ./backend/conference-service/.env
    environment:
      DATABASE_URL: mysql+pymysql://root:root@conference-db:3306/conference_db


  intelligent-db:
      image: mysql:8.0
      container_name: intelligent_db
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: intelligent_db
      ports:
        - "3310:3306"
      volumes:
        - intelligent_db_data:/var/lib/mysql

  intelligent-service:
      build: ./backend/intelligent-service
      container_name: intelligent_service
      restart: on-failure
      ports:
        - "8004:8004"
      depends_on:
        - intelligent-db
      env_file:
        - ./backend/intelligent-service/.env
      environment:
        DATABASE_URL: mysql+pymysql://root:root@intelligent-db:3306/intelligent_db
        GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      volumes:
        - ./backend/intelligent-service/src:/app/src

volumes:
  submission_db_data:
  notification_db_data:
  conference_db_data:
  intelligent_db_data:


